name: wargaming-tasks workflow

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        # обновление pip
        python -m pip install --upgrade pip
        # установка flake8 и его плагинов
        # установка зависимостей
        pip install -r requirements.txt

    - name: Test with unittest, flake8 and mypy
      run: |
        python -m unittest
        cd tasks
        # запуск проверки проекта по flake8
        flake8 task1.py task2.py task3.py
        # запуск проверки проекта по mypy
        mypy task1.py task2.py task3.py

  send_message:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: send message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: ${{ github.workflow }} успешно выполнен!